### ISSUE TITLE
when exec  installContra.sh occur many error

### ISSUE THREAD

**Issue by a220106** [alex1230608/contra#1]
data/temple.xml not found

**Comment by alex1230608** [comment]
> data/temple.xml not found

Hi,
Thank you for trying our work!
Can you be more specific about the errors?
What kind of error messages did you see?
Also, have you followed the Overview and the Environment Setup sections in `README.md`?
Note that you don't have to clone this repo manually. Instead, you should follow the instructions in "Environment Setup" section to set up the CloudLab environment and install the related packages with `packages.sh` (including this repo).
After the above, you can finally run the `installConstra.sh` to create the Contra compiler.

Hope the above helps!

**Comment by liorze** [comment]
Hi, I'm not the OP, but I get the same compilation error:

```
Topology.fs(138,13): error FS3033: The type provider 'ProviderImplementation.XmlProvider' reported an error: Cannot read sample XML from '../data/template.xml'
```

I guess that a sample topology xml file is missing from the tree.

**Comment by alex1230608** [comment]
I see. Sorry for the missing file.
I just added the file and updated the repository.
I tried it on a clean machine and it is working now.
Please try again and let me know if there is any other issue.
Thank you!
