### ISSUE TITLE
Readme second step ~/.ssh/authorized_keys

### ISSUE THREAD

**Issue by l-x007** [alex1230608/contra#2]
How can I achieve the second step in Readme？
I cant run ~/.ssh/authorized_keys

**Comment by alex1230608** [comment]
Hi, ~/.ssh/authorized_keys is not a command. Instead, it's just a file storing all the ssh keys that the server accepts. The second step actually has three sub-steps, and after all the three sub-steps, all the CLXX machines will be able to ssh each other.

**Comment by l-x007** [comment]
Thank you for your reply.But in the second sub-steps,I do not have the ~/.ssh/config file,so Ido not know the nodes' name CL*,what can i do to know the node' name?

**Comment by alex1230608** [comment]
~/.ssh/config is just to setup an alias to the host's ip address so that you can ssh them more easily. Try to search on the internet on how to set up the alias in ~/.ssh/config.
