### ISSUE TITLE
util

### ISSUE THREAD

**Issue by flash6666** [alex1230608/contra#5]
I want to ask how is the path utilization calculated?

**Comment by alex1230608** [comment]
We based our calculation of the util metric on the Hula paper: https://dl.acm.org/doi/10.1145/2890955.2890968

In section 4.2, they have detailed explanation on how a probe carries path utilization which is computed from link utilization along the path, i.e., the bottlenecked link's link utilization, max(util). It also describes how we get the best path based on the minimum path utilization across all probes.

Figure 3 in the paper also shows the p4-like codes.

Note the main difference between Hula and Contra is that Hula's probes travel on predefined paths on a structural topology, while Contra automatically identifies legal paths based on the user policies. In the generated P4 codes from Contra compiler, the packets are constrained to these legal paths by the tag techniques. See Contra paper for more detail. Thanks!

**Comment by flash6666** [comment]
The threshold of δ is LOOP_THRESHOLD = 3, How should this threshold be set reasonably? I don't understand why the threshold is set to 3.
